services:
  application:
    build: .
    image: spring-boot-mysql-app
    container_name: spring-container
    ports:
      - "8080:8080"
    networks:
      - docker-mysql
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb-container
    ports:
      - "3306:3306"
    networks:
      - docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sbms
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  docker-mysql:
